/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compiladorplf;

/**
 *
 * @author fvarg
 */
public class IDEE extends javax.swing.JFrame {

    /**
     * Creates new form IDEE
     */
    public IDEE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Compilar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();
        btn_reservadas = new javax.swing.JButton();
        btn_indentado = new javax.swing.JButton();
        btn_tokens = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCompile = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtp_Code = new javax.swing.JTextPane();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Compilar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Compilar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_Compilar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Compilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8_code_48px.png"))); // NOI18N
        btn_Compilar.setText("Compilar");
        btn_Compilar.setToolTipText("Compilar Codigo");
        btn_Compilar.setBorderPainted(false);
        btn_Compilar.setContentAreaFilled(false);
        btn_Compilar.setFocusPainted(false);
        btn_Compilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Compilar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8_code_48px_p.png"))); // NOI18N
        btn_Compilar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8_code_48px_on.png"))); // NOI18N
        btn_Compilar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_Compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CompilarActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(0, 0, 0));
        btn_nuevo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8_code_file_48px.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setToolTipText("Nuevo documento");
        btn_nuevo.setBorderPainted(false);
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setFocusPainted(false);
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8_code_file_48px_p.png"))); // NOI18N
        btn_nuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8_code_file_48px_on.png"))); // NOI18N
        btn_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btn_guardar.setBackground(new java.awt.Color(0, 0, 0));
        btn_guardar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8_save_48px.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setToolTipText("Guardar documento");
        btn_guardar.setBorderPainted(false);
        btn_guardar.setContentAreaFilled(false);
        btn_guardar.setFocusPainted(false);
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8_save_48px_p.png"))); // NOI18N
        btn_guardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8_save_48px_on.png"))); // NOI18N
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btn_abrir.setBackground(new java.awt.Color(0, 0, 0));
        btn_abrir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_abrir.setForeground(new java.awt.Color(255, 255, 255));
        btn_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8_opened_folder_48px.png"))); // NOI18N
        btn_abrir.setText("Abrir");
        btn_abrir.setToolTipText("Abrir Documento");
        btn_abrir.setBorderPainted(false);
        btn_abrir.setContentAreaFilled(false);
        btn_abrir.setFocusPainted(false);
        btn_abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_abrir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8_opened_folder_48px_P.png"))); // NOI18N
        btn_abrir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8_opened_folder_48px_ON.png"))); // NOI18N
        btn_abrir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btn_reservadas.setBackground(new java.awt.Color(0, 0, 0));
        btn_reservadas.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_reservadas.setForeground(new java.awt.Color(255, 255, 255));
        btn_reservadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8-text-color-48.png"))); // NOI18N
        btn_reservadas.setText("Reservadas");
        btn_reservadas.setToolTipText("Palabras Reservadas");
        btn_reservadas.setBorderPainted(false);
        btn_reservadas.setContentAreaFilled(false);
        btn_reservadas.setFocusPainted(false);
        btn_reservadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reservadas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8-text-color-48.png"))); // NOI18N
        btn_reservadas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8-text-color-48.png"))); // NOI18N
        btn_reservadas.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btn_indentado.setBackground(new java.awt.Color(0, 0, 0));
        btn_indentado.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_indentado.setForeground(new java.awt.Color(255, 255, 255));
        btn_indentado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8-text-cursor-48.png"))); // NOI18N
        btn_indentado.setText("Indentar");
        btn_indentado.setToolTipText("Indentar Documento");
        btn_indentado.setBorderPainted(false);
        btn_indentado.setContentAreaFilled(false);
        btn_indentado.setFocusPainted(false);
        btn_indentado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_indentado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8-text-cursor-48.png"))); // NOI18N
        btn_indentado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8-text-cursor-48.png"))); // NOI18N
        btn_indentado.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btn_tokens.setBackground(new java.awt.Color(0, 0, 0));
        btn_tokens.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btn_tokens.setForeground(new java.awt.Color(255, 255, 255));
        btn_tokens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/icons8-index-48.png"))); // NOI18N
        btn_tokens.setText("Tokens");
        btn_tokens.setToolTipText("Tokens");
        btn_tokens.setBorderPainted(false);
        btn_tokens.setContentAreaFilled(false);
        btn_tokens.setFocusPainted(false);
        btn_tokens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tokens.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pressed/icons8-index-48.png"))); // NOI18N
        btn_tokens.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/On Layer/icons8-index-48.png"))); // NOI18N
        btn_tokens.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jtaCompile.setEditable(false);
        jtaCompile.setColumns(20);
        jtaCompile.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jtaCompile.setRows(5);
        jtaCompile.setToolTipText("");
        jScrollPane2.setViewportView(jtaCompile);

        jtp_Code.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jtp_Code.setToolTipText("");
        jScrollPane3.setViewportView(jtp_Code);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Icon/fondo1.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_reservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_indentado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_tokens, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(680, 680, 680)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(290, 290, 290)
                            .addComponent(btn_reservadas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btn_indentado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(btn_Compilar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(470, 470, 470)
                            .addComponent(btn_tokens, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(btn_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CompilarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CompilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDEE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDEE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Compilar;
    private javax.swing.JButton btn_abrir;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_indentado;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_reservadas;
    private javax.swing.JButton btn_tokens;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jtaCompile;
    private javax.swing.JTextPane jtp_Code;
    // End of variables declaration//GEN-END:variables
}
